const fs = require("fs");
const transporter = require("../util/mailTransporter");

const COMPANY = {
  name: "Bharat Special Steels Pvt. Ltd.",
  address:
    "107, First Floor, SSR Corporate Tower, near NHPC Metro, Faridabad, Haryana 121003",
};

const formatCurrency = (amount) => {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 2,
  }).format(Number(amount || 0));
};

const formatDate = (date) => {
  if (!date) return "-";
  return new Date(date).toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
};

const cleanEmails = (emails = []) => {
  return [
    ...new Set(
      emails
        .filter(Boolean)
        .map((email) => String(email).trim().toLowerCase())
        .filter((email) => email.includes("@"))
    ),
  ];
};

const getDispatchAttachments = (dispatch) => {
  const attachments = [];

  if (dispatch.billPdf?.filePath && fs.existsSync(dispatch.billPdf.filePath)) {
    attachments.push({
      filename: dispatch.billPdf.originalName || dispatch.billPdf.fileName,
      path: dispatch.billPdf.filePath,
    });
  }

  if (
    dispatch.lrCopyPdf?.filePath &&
    fs.existsSync(dispatch.lrCopyPdf.filePath)
  ) {
    attachments.push({
      filename: dispatch.lrCopyPdf.originalName || dispatch.lrCopyPdf.fileName,
      path: dispatch.lrCopyPdf.filePath,
    });
  }

  return attachments;
};

const baseEmailTemplate = ({ title, subtitle, bodyContent }) => {
  return `
  <!DOCTYPE html>
  <html>
  <head>
    <meta charset="UTF-8" />
    <style>
      body {
        margin: 0;
        padding: 0;
        background: #f3f6fb;
        font-family: Arial, Helvetica, sans-serif;
        color: #1f2937;
      }

      .wrapper {
        width: 100%;
        padding: 24px 0;
        background: #f3f6fb;
      }

      .container {
        max-width: 720px;
        margin: 0 auto;
        background: #ffffff;
        border-radius: 14px;
        overflow: hidden;
        border: 1px solid #e5e7eb;
      }

      .header {
        background: linear-gradient(135deg, #0f172a, #1e3a8a);
        padding: 24px 28px;
        color: #ffffff;
      }

      .header h1 {
        margin: 0;
        font-size: 22px;
        letter-spacing: 0.2px;
      }

      .header p {
        margin: 8px 0 0;
        font-size: 14px;
        color: #dbeafe;
      }

      .content {
        padding: 28px;
      }

      .notice {
        background: #eff6ff;
        border-left: 4px solid #2563eb;
        padding: 14px 16px;
        border-radius: 10px;
        margin-bottom: 22px;
        font-size: 14px;
        line-height: 1.55;
      }

      table {
        width: 100%;
        border-collapse: collapse;
        margin: 18px 0;
      }

      td {
        padding: 11px 12px;
        border-bottom: 1px solid #e5e7eb;
        font-size: 14px;
        vertical-align: top;
      }

      td.label {
        width: 38%;
        background: #f8fafc;
        font-weight: 700;
        color: #475569;
      }

      td.value {
        color: #111827;
        font-weight: 600;
      }

      .amount-box {
        background: #f8fafc;
        border: 1px solid #e5e7eb;
        border-radius: 12px;
        padding: 16px;
        margin-top: 16px;
      }

      .amount-row {
        display: flex;
        justify-content: space-between;
        padding: 7px 0;
        font-size: 14px;
      }

      .amount-row strong {
        color: #111827;
      }

      .pending {
        color: #b91c1c;
        font-weight: 800;
      }

      .paid {
        color: #15803d;
        font-weight: 800;
      }

      .footer {
        padding: 20px 28px;
        background: #f8fafc;
        border-top: 1px solid #e5e7eb;
        font-size: 12px;
        color: #64748b;
        line-height: 1.6;
      }

      .company {
        font-weight: 800;
        color: #0f172a;
        font-size: 13px;
      }

      .auto {
        margin-top: 12px;
        font-style: italic;
        color: #94a3b8;
      }
    </style>
  </head>

  <body>
    <div class="wrapper">
      <div class="container">
        <div class="header">
          <h1>${title}</h1>
          <p>${subtitle}</p>
        </div>

        <div class="content">
          ${bodyContent}
        </div>

        <div class="footer">
          <div class="company">${COMPANY.name}</div>
          <div>${COMPANY.address}</div>
          <div class="auto">
            This is an automated notification generated by Bharat RMS. Please do not reply to this email directly.
          </div>
        </div>
      </div>
    </div>
  </body>
  </html>
  `;
};

const buildDispatchCreatedTemplate = (dispatch) => {
  return baseEmailTemplate({
    title: "Material Dispatch Notification",
    subtitle: `${COMPANY.name} | Dispatch Confirmation`,
    bodyContent: `
      <div class="notice">
        Dear ${dispatch.contactPersonName || "Customer"},<br/><br/>
        We are pleased to inform you that your material against the below order has been dispatched.
        The tax invoice/bill set and LR copy are attached with this email for your records.
      </div>

      <table>
        <tr>
          <td class="label">Company Name</td>
          <td class="value">${dispatch.companyName || "-"}</td>
        </tr>
        <tr>
          <td class="label">Sales Order No.</td>
          <td class="value">${dispatch.salesOrderNo || "-"}</td>
        </tr>
        <tr>
          <td class="label">PO Number</td>
          <td class="value">${dispatch.poNumber || "-"}</td>
        </tr>
        <tr>
          <td class="label">Invoice Number</td>
          <td class="value">${dispatch.invoiceNumber || "-"}</td>
        </tr>
        <tr>
          <td class="label">Invoice Date</td>
          <td class="value">${formatDate(dispatch.invoiceDate)}</td>
        </tr>
        <tr>
          <td class="label">Dispatch Date</td>
          <td class="value">${formatDate(dispatch.dispatchDate)}</td>
        </tr>
        <tr>
          <td class="label">Dispatch Quantity</td>
          <td class="value">${dispatch.dispatchQty || 0} Kg</td>
        </tr>
        <tr>
          <td class="label">Invoice Value</td>
          <td class="value">${formatCurrency(dispatch.invoiceValue)}</td>
        </tr>
        <tr>
          <td class="label">LR Number</td>
          <td class="value">${dispatch.lrNumber || "-"}</td>
        </tr>
        <tr>
          <td class="label">Payment Due Date</td>
          <td class="value">${formatDate(dispatch.paymentDueDate)}</td>
        </tr>
      </table>

      <div class="amount-box">
        <div class="amount-row">
          <span>Invoice Amount</span>
          <strong>${formatCurrency(dispatch.invoiceValue)}</strong>
        </div>
        <div class="amount-row">
          <span>Paid Amount</span>
          <strong class="paid">${formatCurrency(dispatch.paidAmount)}</strong>
        </div>
        <div class="amount-row">
          <span>Pending Amount</span>
          <strong class="pending">${formatCurrency(dispatch.pendingAmount)}</strong>
        </div>
      </div>
    `,
  });
};

const buildPaymentUpdateTemplate = (dispatch, payment) => {
  return baseEmailTemplate({
    title: "Payment Update Notification",
    subtitle: `${COMPANY.name} | Accounts Update`,
    bodyContent: `
      <div class="notice">
        Dear ${dispatch.contactPersonName || "Customer"},<br/><br/>
        This is to confirm that a payment update has been recorded against your dispatched invoice.
        Please find the updated payment summary below.
      </div>

      <table>
        <tr>
          <td class="label">Company Name</td>
          <td class="value">${dispatch.companyName || "-"}</td>
        </tr>
        <tr>
          <td class="label">Invoice Number</td>
          <td class="value">${dispatch.invoiceNumber || "-"}</td>
        </tr>
        <tr>
          <td class="label">Invoice Date</td>
          <td class="value">${formatDate(dispatch.invoiceDate)}</td>
        </tr>
        <tr>
          <td class="label">Payment Due Date</td>
          <td class="value">${formatDate(dispatch.paymentDueDate)}</td>
        </tr>
        <tr>
          <td class="label">Payment Status</td>
          <td class="value">${String(dispatch.paymentStatus || "-").toUpperCase()}</td>
        </tr>
      </table>

      <div class="amount-box">
        <div class="amount-row">
          <span>Invoice Amount</span>
          <strong>${formatCurrency(dispatch.invoiceValue)}</strong>
        </div>
        <div class="amount-row">
          <span>Payment Received Now</span>
          <strong class="paid">${formatCurrency(payment.amount)}</strong>
        </div>
        <div class="amount-row">
          <span>Total Paid Amount</span>
          <strong class="paid">${formatCurrency(dispatch.paidAmount)}</strong>
        </div>
        <div class="amount-row">
          <span>Pending Amount</span>
          <strong class="pending">${formatCurrency(dispatch.pendingAmount)}</strong>
        </div>
      </div>

      ${
        payment.remark
          ? `<div class="notice" style="margin-top:18px;">Remark: ${payment.remark}</div>`
          : ""
      }
    `,
  });
};

const sendDispatchCreatedEmail = async (dispatch) => {
  const to = dispatch.contactPersonEmail;

  const cc = cleanEmails(dispatch.notificationEmail?.cc || []);

  const attachments = getDispatchAttachments(dispatch);

  const mail = await transporter.sendMail({
    from: `"${COMPANY.name}" <${process.env.ADMIN_EMAIL}>`,
    to,
    cc,
    subject: `Dispatch Confirmation | Invoice ${dispatch.invoiceNumber} | ${dispatch.companyName}`,
    html: buildDispatchCreatedTemplate(dispatch),
    attachments,
  });

  return mail;
};

const sendPaymentUpdateEmail = async (dispatch, payment) => {
  const to = dispatch.contactPersonEmail;

  const cc = cleanEmails([
    dispatch.salesPersonEmail,
    ...(dispatch.notificationEmail?.cc || []),
  ]);

  const mail = await transporter.sendMail({
    from: `"${COMPANY.name}" <${process.env.ADMIN_EMAIL}>`,
    to,
    cc,
    subject: `Payment Update | Invoice ${dispatch.invoiceNumber} | Pending ${formatCurrency(
      dispatch.pendingAmount
    )}`,
    html: buildPaymentUpdateTemplate(dispatch, payment),
  });

  return mail;
};

module.exports = {
  sendDispatchCreatedEmail,
  sendPaymentUpdateEmail,
};