/* =========================================================
   FILE:
   util/sbeGermanyConfig.js

   PURPOSE:

   Central configuration for SBE Germany MTC.

   IMPORTANT DESIGN:

   Frontend user selects:
   - Grade

   User may edit ONLY:
   - Customer Name
   - Quantity / Anzahl
   - Dimension / Abmessung

   Everything else comes from this configuration
   or is automatically generated by backend.

========================================================= */


/* =========================================================
   COMMON FIXED SBE VALUES

   These values should NOT be editable from frontend.
========================================================= */

const SBE_FIXED_VALUES = {
  position: "577",

  quantityUnit: "ST",

  meltingMethod: "Elektrostahl",

  castingProcess: "Blockguß",

  materialRemark:
    "Rest-uhd Anschnittstucke",

  ultrasonicTest: "Ok",

  cleanlinessRating: "Ok",

  meltingProcess: "EAF+LHF+VD",

  macroMicroStructure: "Ok",
};


/* =========================================================
   CHEMICAL ELEMENT ORDER

   Must remain exactly in SBE PDF order.
========================================================= */

const SBE_CHEMICAL_ORDER = [
  "C",
  "Si",
  "Mn",
  "Cr",
  "S",
  "P",
  "V",
  "Mo",
  "Ni",
  "Al",
  "Cu",
];


/* =========================================================
   SBE GRADE MASTER

   IMPORTANT:

   This is the ONLY source used for:

   - Material Code
   - Werkstoff
   - Material Description
   - Ausführung
   - Chemical Composition
   - Hardness

   Frontend should NOT allow the user to manually change
   these values.

========================================================= */

const SBE_GRADE_CONFIG = {
  /* =======================================================
     DIN 1.2714

     Values taken from the SBE TC data supplied.
  ======================================================= */

  "1.2714": {
    grade: "1.2714",

    materialCode: "1.2714",

    materialDescription:
      "Wst 1.2714 geschmiedet",

    execution: "1.2714",

    /*
     * SBE TC achieved chemical values.
     */
    chemicalComposition: [
      {
        element: "C",
        min: null,
        max: null,
        result: 0.54,
      },

      {
        element: "Si",
        min: null,
        max: null,
        result: 0.26,
      },

      {
        element: "Mn",
        min: null,
        max: null,
        result: 0.71,
      },

      {
        element: "Cr",
        min: null,
        max: null,
        result: 1.13,
      },

      {
        element: "S",
        min: null,
        max: null,
        result: 0.001,
      },

      {
        element: "P",
        min: null,
        max: null,
        result: 0.014,
      },

      {
        element: "V",
        min: null,
        max: null,
        result: 0.09,
      },

      {
        element: "Mo",
        min: null,
        max: null,
        result: 0.46,
      },

      {
        element: "Ni",
        min: null,
        max: null,
        result: 1.58,
      },

      {
        element: "Al",
        min: null,
        max: null,
        result: "---",
      },

      {
        element: "Cu",
        min: null,
        max: null,
        result: "---",
      },
    ],

    hardnessBHN: "396",
  },


  /* =======================================================
     DIN 1.2738

     Chemical values taken from the supplied SBE data.

     IMPORTANT:
     Hardness is intentionally NOT invented here.
     Put the confirmed SBE hardness value once available.
  ======================================================= */

  "1.2738": {
    grade: "1.2738",

    materialCode: "1.2738",

    materialDescription:
      "Wst 1.2738 geschmiedet",

    execution: "1.2738",

    chemicalComposition: [
      {
        element: "C",
        min: null,
        max: null,
        result: 0.38,
      },

      {
        element: "Si",
        min: null,
        max: null,
        result: 0.32,
      },

      {
        element: "Mn",
        min: null,
        max: null,
        result: 1.50,
      },

      {
        element: "Cr",
        min: null,
        max: null,
        result: 1.90,
      },

      {
        element: "S",
        min: null,
        max: null,
        result: 0.003,
      },

      {
        element: "P",
        min: null,
        max: null,
        result: 0.011,
      },

      {
        element: "V",
        min: null,
        max: null,
        result: 0.030,
      },

      {
        element: "Mo",
        min: null,
        max: null,
        result: 0.20,
      },

      {
        element: "Ni",
        min: null,
        max: null,
        result: 0.94,
      },

      {
        element: "Al",
        min: null,
        max: null,
        result: 0.020,
      },

      {
        element: "Cu",
        min: null,
        max: null,
        result: 0.14,
      },
    ],

    /*
     * Set this only after confirming the actual
     * SBE certificate hardness.
     */
    hardnessBHN: "",
  },


  /* =======================================================
     DIN 1.2379

     Chemical values visible in supplied SBE reference.

     Add/confirm hardness separately if required.
  ======================================================= */

  "1.2379": {
    grade: "1.2379",

    materialCode: "1.2379",

    materialDescription:
      "Wst 1.2379 geschmiedet",

    execution: "1.2379",

    chemicalComposition: [
      {
        element: "C",
        min: null,
        max: null,
        result: 1.53,
      },

      {
        element: "Si",
        min: null,
        max: null,
        result: 0.26,
      },

      {
        element: "Mn",
        min: null,
        max: null,
        result: 0.32,
      },

      {
        element: "Cr",
        min: null,
        max: null,
        result: 11.14,
      },

      {
        element: "S",
        min: null,
        max: null,
        result: 0.026,
      },

      {
        element: "P",
        min: null,
        max: null,
        result: 0.028,
      },

      {
        element: "V",
        min: null,
        max: null,
        result: 0.75,
      },

      {
        element: "Mo",
        min: null,
        max: null,
        result: 0.76,
      },

      {
        element: "Ni",
        min: null,
        max: null,
        result: "---",
      },

      {
        element: "Al",
        min: null,
        max: null,
        result: "---",
      },

      {
        element: "Cu",
        min: null,
        max: null,
        result: "---",
      },
    ],

    hardnessBHN: "",
  },
};


/* =========================================================
   GET ONE GRADE CONFIG
========================================================= */

const getSbeGradeConfig = (
  grade
) => {
  const cleanGrade =
    String(grade || "").trim();

  if (!cleanGrade) {
    throw new Error(
      "SBE Germany grade is required"
    );
  }

  const config =
    SBE_GRADE_CONFIG[
      cleanGrade
    ];

  if (!config) {
    throw new Error(
      `SBE Germany configuration not found for grade ${cleanGrade}`
    );
  }

  /*
   * Deep clone so callers cannot accidentally
   * modify the master configuration.
   */
  return JSON.parse(
    JSON.stringify(config)
  );
};


/* =========================================================
   GET AVAILABLE GRADES

   Frontend dropdown should use ONLY this.
========================================================= */

const getSbeGrades = () => {
  return Object.keys(
    SBE_GRADE_CONFIG
  ).map((grade) => ({
    value: grade,
    label: grade,
  }));
};


/* =========================================================
   BUILD COMPLETE AUTO-POPULATED FORM

   Frontend calls provider config and uses this
   once a grade is selected.

   Only editable fields:
   - customerName
   - quantity
   - dimension
========================================================= */

const buildSbeGradeFormData = (
  grade
) => {
  const gradeConfig =
    getSbeGradeConfig(
      grade
    );

  return {
    mtcProvider:
      "sbe_germany",

    grade:
      gradeConfig.grade,

    /* =====================================
       FIXED VALUES
    ===================================== */

    position:
      SBE_FIXED_VALUES.position,

    quantityUnit:
      SBE_FIXED_VALUES.quantityUnit,

    meltingMethod:
      SBE_FIXED_VALUES.meltingMethod,

    castingProcess:
      SBE_FIXED_VALUES.castingProcess,

    materialRemark:
      SBE_FIXED_VALUES.materialRemark,

    ultrasonicTest:
      SBE_FIXED_VALUES.ultrasonicTest,

    cleanlinessRating:
      SBE_FIXED_VALUES.cleanlinessRating,

    meltingProcess:
      SBE_FIXED_VALUES.meltingProcess,

    macroMicroStructure:
      SBE_FIXED_VALUES.macroMicroStructure,

    /* =====================================
       GRADE-CONTROLLED VALUES
    ===================================== */

    materialCode:
      gradeConfig.materialCode,

    materialDescription:
      gradeConfig.materialDescription,

    execution:
      gradeConfig.execution,

    chemicalComposition:
      gradeConfig.chemicalComposition,

    chemicalOrder:
      [...SBE_CHEMICAL_ORDER],

    hardnessBHN:
      gradeConfig.hardnessBHN,

    /* =====================================
       USER EDITABLE VALUES

       Empty until frontend/user enters them.
    ===================================== */

    customerName: "",

    quantity: "1",

    dimension: "",

    /*
     * GENERATED BY BACKEND DURING CREATE.
     * Do not provide inputs for these.
     */
    productionOrder: "",

    customerPoNumber: "",
  };
};


/* =========================================================
   FRONTEND FIELD PERMISSIONS

   Grade is selectable when creating a new TC.

   Once the user selects the grade:
   all dependent values are read-only.

========================================================= */

const SBE_FRONTEND_PERMISSIONS = {
  /*
   * Selectable using dropdown.
   */
  selectable: [
    "grade",
  ],

  /*
   * User may type/change these.
   */
  editable: [
    "customerName",
    "quantity",
    "dimension",
  ],

  /*
   * Display if desired, but never allow editing.
   */
  readOnly: [
    "position",
    "quantityUnit",

    "meltingMethod",
    "castingProcess",

    "materialCode",
    "materialDescription",
    "materialRemark",
    "execution",

    "chemicalComposition",
    "hardnessBHN",

    "ultrasonicTest",
    "cleanlinessRating",
    "meltingProcess",
    "macroMicroStructure",

    "productionOrder",
    "customerPoNumber",
  ],

  /*
   * These can be completely hidden from frontend input form.
   */
  generated: [
    "productionOrder",
    "customerPoNumber",
  ],
};


/* =========================================================
   VALIDATE USER-EDITABLE SBE DATA

   Backend validation is important.
   Frontend validation alone is not enough.
========================================================= */

const validateSbeEditableFields = (
  payload = {}
) => {
  const errors = [];

  const grade =
    String(
      payload.grade || ""
    ).trim();

  const customerName =
    String(
      payload.customerName ||
        ""
    ).trim();

  const quantity =
    String(
      payload.quantity ||
        payload.pcs ||
        ""
    ).trim();

  const dimension =
    String(
      payload.dimension ||
        payload.size ||
        ""
    ).trim();


  /* =======================================================
     GRADE
  ======================================================= */

  if (!grade) {
    errors.push(
      "Grade is required"
    );
  } else if (
    !SBE_GRADE_CONFIG[
      grade
    ]
  ) {
    errors.push(
      `Invalid SBE Germany grade: ${grade}`
    );
  }


  /* =======================================================
     CUSTOMER
  ======================================================= */

  if (!customerName) {
    errors.push(
      "Customer Name is required"
    );
  }


  /* =======================================================
     QUANTITY
  ======================================================= */

  if (!quantity) {
    errors.push(
      "Quantity is required"
    );
  } else {
    const numericQuantity =
      Number(quantity);

    if (
      Number.isNaN(
        numericQuantity
      ) ||
      numericQuantity <= 0
    ) {
      errors.push(
        "Quantity must be greater than 0"
      );
    }
  }


  /* =======================================================
     DIMENSION
  ======================================================= */

  if (!dimension) {
    errors.push(
      "Dimension is required"
    );
  }


  if (errors.length) {
    throw new Error(
      errors.join(", ")
    );
  }

  return true;
};


/* =========================================================
   EXPORT
========================================================= */

module.exports = {
  SBE_FIXED_VALUES,

  SBE_CHEMICAL_ORDER,

  SBE_GRADE_CONFIG,

  SBE_FRONTEND_PERMISSIONS,

  getSbeGradeConfig,

  getSbeGrades,

  buildSbeGradeFormData,

  validateSbeEditableFields,
};