/* =========================================================
   FILE:
   util/sbeGermanyConfig.js

   PURPOSE:

   Central configuration for SBE Germany MTC.

   IMPORTANT DESIGN:

   Frontend user selects:
   - Grade

   User may edit ONLY:
   - Customer Name
   - Quantity / Anzahl
   - Dimension / Abmessung

   Everything else comes from this configuration
   or is automatically generated by backend.
========================================================= */


/* =========================================================
   PROVIDER
========================================================= */

const SBE_PROVIDER =
  "sbe_germany";


/* =========================================================
   COMMON FIXED SBE VALUES

   These values should NOT be editable from frontend.
========================================================= */

const SBE_FIXED_VALUES = {
  position:
    "577",

  quantityUnit:
    "ST",

  meltingMethod:
    "Elektrostahl",

  castingProcess:
    "Blockguß",

  materialRemark:
    "Rest-uhd Anschnittstucke",

  ultrasonicTest:
    "Ok",

  cleanlinessRating:
    "Ok",

  meltingProcess:
    "EAF+LHF+VD",

  macroMicroStructure:
    "Ok",

  /*
   * Fixed supply condition for
   * current SBE Germany certificates.
   */
  condition:
    "Forged",
};


/* =========================================================
   CHEMICAL ELEMENT ORDER

   Must remain exactly in SBE PDF order.
========================================================= */

const SBE_CHEMICAL_ORDER = [
  "C",
  "Si",
  "Mn",
  "Cr",
  "S",
  "P",
  "V",
  "Mo",
  "Ni",
  "Al",
  "Cu",
];


/* =========================================================
   SBE GRADE MASTER

   IMPORTANT:

   This is the ONLY source used for:

   - Material Code
   - Werkstoff
   - Material Description
   - Ausführung
   - Chemical Composition
   - Hardness

   Frontend should NOT allow the user to manually change
   these values.
========================================================= */

const SBE_GRADE_CONFIG = {
  /* =======================================================
     DIN 1.2714

     KEEPING YOUR EXISTING VALUES EXACTLY.
  ======================================================= */

  "1.2714": {
    grade:
      "1.2714",

    materialCode:
      "1.2714",

    materialDescription:
      "Wst 1.2714 geschmiedet",

    execution:
      "1.2714",

    chemicalComposition: [
      {
        element:
          "C",
        min:
          null,
        max:
          null,
        result:
          0.54,
      },

      {
        element:
          "Si",
        min:
          null,
        max:
          null,
        result:
          0.26,
      },

      {
        element:
          "Mn",
        min:
          null,
        max:
          null,
        result:
          0.71,
      },

      {
        element:
          "Cr",
        min:
          null,
        max:
          null,
        result:
          1.13,
      },

      {
        element:
          "S",
        min:
          null,
        max:
          null,
        result:
          0.001,
      },

      {
        element:
          "P",
        min:
          null,
        max:
          null,
        result:
          0.014,
      },

      {
        element:
          "V",
        min:
          null,
        max:
          null,
        result:
          0.09,
      },

      {
        element:
          "Mo",
        min:
          null,
        max:
          null,
        result:
          0.46,
      },

      {
        element:
          "Ni",
        min:
          null,
        max:
          null,
        result:
          1.58,
      },

      {
        element:
          "Al",
        min:
          null,
        max:
          null,
        result:
          "---",
      },

      {
        element:
          "Cu",
        min:
          null,
        max:
          null,
        result:
          "---",
      },
    ],

    hardnessBHN:
      "396",
  },


  /* =======================================================
     DIN 1.2738

     KEEPING YOUR EXISTING VALUES EXACTLY.

     Hardness remains blank because it has not
     been confirmed in your existing config.
  ======================================================= */

  "1.2738": {
    grade:
      "1.2738",

    materialCode:
      "1.2738",

    materialDescription:
      "Wst 1.2738 geschmiedet",

    execution:
      "1.2738",

    chemicalComposition: [
      {
        element:
          "C",
        min:
          null,
        max:
          null,
        result:
          0.38,
      },

      {
        element:
          "Si",
        min:
          null,
        max:
          null,
        result:
          0.32,
      },

      {
        element:
          "Mn",
        min:
          null,
        max:
          null,
        result:
          1.50,
      },

      {
        element:
          "Cr",
        min:
          null,
        max:
          null,
        result:
          1.90,
      },

      {
        element:
          "S",
        min:
          null,
        max:
          null,
        result:
          0.003,
      },

      {
        element:
          "P",
        min:
          null,
        max:
          null,
        result:
          0.011,
      },

      {
        element:
          "V",
        min:
          null,
        max:
          null,
        result:
          0.030,
      },

      {
        element:
          "Mo",
        min:
          null,
        max:
          null,
        result:
          0.20,
      },

      {
        element:
          "Ni",
        min:
          null,
        max:
          null,
        result:
          0.94,
      },

      {
        element:
          "Al",
        min:
          null,
        max:
          null,
        result:
          0.020,
      },

      {
        element:
          "Cu",
        min:
          null,
        max:
          null,
        result:
          0.14,
      },
    ],

    hardnessBHN:
      "",
  },


  /* =======================================================
     DIN 1.2379

     KEEPING YOUR EXISTING VALUES EXACTLY.

     Hardness remains blank because it has not
     been confirmed in your existing config.
  ======================================================= */

  "1.2379": {
    grade:
      "1.2379",

    materialCode:
      "1.2379",

    materialDescription:
      "Wst 1.2379 geschmiedet",

    execution:
      "1.2379",

    chemicalComposition: [
      {
        element:
          "C",
        min:
          null,
        max:
          null,
        result:
          1.53,
      },

      {
        element:
          "Si",
        min:
          null,
        max:
          null,
        result:
          0.26,
      },

      {
        element:
          "Mn",
        min:
          null,
        max:
          null,
        result:
          0.32,
      },

      {
        element:
          "Cr",
        min:
          null,
        max:
          null,
        result:
          11.14,
      },

      {
        element:
          "S",
        min:
          null,
        max:
          null,
        result:
          0.026,
      },

      {
        element:
          "P",
        min:
          null,
        max:
          null,
        result:
          0.028,
      },

      {
        element:
          "V",
        min:
          null,
        max:
          null,
        result:
          0.75,
      },

      {
        element:
          "Mo",
        min:
          null,
        max:
          null,
        result:
          0.76,
      },

      {
        element:
          "Ni",
        min:
          null,
        max:
          null,
        result:
          "---",
      },

      {
        element:
          "Al",
        min:
          null,
        max:
          null,
        result:
          "---",
      },

      {
        element:
          "Cu",
        min:
          null,
        max:
          null,
        result:
          "---",
      },
    ],

    hardnessBHN:
      "",
  },
};


/* =========================================================
   BASIC HELPERS
========================================================= */

const cleanText = (
  value
) => {
  if (
    value === null ||
    value === undefined
  ) {
    return "";
  }

  return String(
    value
  ).trim();
};


const cloneData = (
  value
) => {
  return JSON.parse(
    JSON.stringify(
      value
    )
  );
};


const isPlainObject = (
  value
) => {
  return (
    value !== null &&
    typeof value ===
      "object" &&
    !Array.isArray(
      value
    )
  );
};


/* =========================================================
   GET ONE GRADE CONFIG
========================================================= */

const getSbeGradeConfig = (
  grade
) => {
  const cleanGrade =
    cleanText(
      grade
    );

  if (
    !cleanGrade
  ) {
    throw new Error(
      "SBE Germany grade is required"
    );
  }

  const config =
    SBE_GRADE_CONFIG[
      cleanGrade
    ];

  if (
    !config
  ) {
    throw new Error(
      `SBE Germany configuration not found for grade ${cleanGrade}`
    );
  }

  /*
   * Deep clone so callers cannot accidentally
   * modify master configuration.
   */
  return cloneData(
    config
  );
};


/* =========================================================
   GET AVAILABLE GRADES

   Frontend dropdown should use ONLY this.
========================================================= */

const getSbeGrades =
  () => {
    return Object.keys(
      SBE_GRADE_CONFIG
    ).map(
      (
        grade
      ) => ({
        value:
          grade,

        label:
          grade,
      })
    );
  };


/* =========================================================
   BUILD COMPLETE AUTO-POPULATED FORM

   Frontend uses this after grade selection.

   Editable:
   - customerName
   - quantity
   - dimension

   Everything else is backend controlled.
========================================================= */

const buildSbeGradeFormData = (
  grade
) => {
  const gradeConfig =
    getSbeGradeConfig(
      grade
    );

  return {
    mtcProvider:
      SBE_PROVIDER,

    grade:
      gradeConfig.grade,

    /* =====================================
       FIXED VALUES
    ===================================== */

    position:
      SBE_FIXED_VALUES
        .position,

    quantityUnit:
      SBE_FIXED_VALUES
        .quantityUnit,

    meltingMethod:
      SBE_FIXED_VALUES
        .meltingMethod,

    castingProcess:
      SBE_FIXED_VALUES
        .castingProcess,

    materialRemark:
      SBE_FIXED_VALUES
        .materialRemark,

    ultrasonicTest:
      SBE_FIXED_VALUES
        .ultrasonicTest,

    cleanlinessRating:
      SBE_FIXED_VALUES
        .cleanlinessRating,

    meltingProcess:
      SBE_FIXED_VALUES
        .meltingProcess,

    macroMicroStructure:
      SBE_FIXED_VALUES
        .macroMicroStructure,

    condition:
      SBE_FIXED_VALUES
        .condition,

    /* =====================================
       GRADE-CONTROLLED VALUES
    ===================================== */

    materialCode:
      gradeConfig
        .materialCode,

    materialDescription:
      gradeConfig
        .materialDescription,

    execution:
      gradeConfig
        .execution,

    chemicalComposition:
      cloneData(
        gradeConfig
          .chemicalComposition
      ),

    chemicalOrder: [
      ...SBE_CHEMICAL_ORDER,
    ],

    hardnessBHN:
      gradeConfig
        .hardnessBHN,

    /* =====================================
       USER EDITABLE VALUES

       Empty/default until user enters them.
    ===================================== */

    customerName:
      "",

    quantity:
      "1",

    dimension:
      "",

    /* =====================================
       GENERATED BY BACKEND

       Never entered manually.
    ===================================== */

    productionOrder:
      "",

    customerPoNumber:
      "",
  };
};


/* =========================================================
   FRONTEND FIELD PERMISSIONS
========================================================= */

const SBE_FRONTEND_PERMISSIONS = {
  /*
   * Grade can be selected only
   * when creating a certificate.
   */
  selectable: [
    "grade",
  ],

  /*
   * User may enter/change these.
   */
  editable: [
    "customerName",
    "quantity",
    "dimension",
  ],

  /*
   * Display only.
   */
  readOnly: [
    "position",
    "quantityUnit",

    "meltingMethod",
    "castingProcess",

    "materialCode",
    "materialDescription",
    "materialRemark",
    "execution",

    "chemicalComposition",
    "chemicalOrder",
    "hardnessBHN",

    "ultrasonicTest",
    "cleanlinessRating",
    "meltingProcess",
    "macroMicroStructure",

    "condition",

    "productionOrder",
    "customerPoNumber",
  ],

  /*
   * Automatically generated by backend.
   */
  generated: [
    "productionOrder",
    "customerPoNumber",
  ],
};


/* =========================================================
   FRONTEND RULES

   New SBE service imports SBE_FRONTEND_RULES.

   Keep permissions separately too so old code remains
   compatible.
========================================================= */

const SBE_FRONTEND_RULES = {
  provider:
    SBE_PROVIDER,

  createEditableFields: [
    "grade",
    "customerName",
    "quantity",
    "dimension",
  ],

  updateEditableFields: [
    "customerName",
    "quantity",
    "dimension",
  ],

  generatedFields: [
    "productionOrder",
    "customerPoNumber",
  ],

  immutableFields: [
    "mtcProvider",

    "grade",

    "productionOrder",
    "customerPoNumber",

    "position",
    "quantityUnit",

    "meltingMethod",
    "castingProcess",

    "materialCode",
    "materialDescription",
    "materialRemark",
    "execution",

    "chemicalComposition",
    "chemicalOrder",
    "hardnessBHN",

    "ultrasonicTest",
    "cleanlinessRating",
    "meltingProcess",
    "macroMicroStructure",

    "condition",
  ],

  selectable: [
    ...SBE_FRONTEND_PERMISSIONS
      .selectable,
  ],

  editable: [
    ...SBE_FRONTEND_PERMISSIONS
      .editable,
  ],

  readOnly: [
    ...SBE_FRONTEND_PERMISSIONS
      .readOnly,
  ],

  generated: [
    ...SBE_FRONTEND_PERMISSIONS
      .generated,
  ],

  controlledByBackend:
    true,
};


/* =========================================================
   VALIDATE COMPLETE EDITABLE DATA

   Kept for backward compatibility.

   Used when all four create fields must exist:
   - grade
   - customerName
   - quantity
   - dimension
========================================================= */

const validateSbeEditableFields = (
  payload = {}
) => {
  const errors = [];

  const grade =
    cleanText(
      payload.grade
    );

  const customerName =
    cleanText(
      payload.customerName
    );

  /*
   * Keep support for old pcs alias.
   */
  const quantity =
    cleanText(
      payload.quantity ??
        payload.pcs
    );

  /*
   * Keep support for old size alias.
   */
  const dimension =
    cleanText(
      payload.dimension ??
        payload.size
    );


  /* =======================================================
     GRADE
  ======================================================= */

  if (
    !grade
  ) {
    errors.push(
      "Grade is required"
    );
  } else if (
    !SBE_GRADE_CONFIG[
      grade
    ]
  ) {
    errors.push(
      `Invalid SBE Germany grade: ${grade}`
    );
  }


  /* =======================================================
     CUSTOMER
  ======================================================= */

  if (
    !customerName
  ) {
    errors.push(
      "Customer Name is required"
    );
  }


  /* =======================================================
     QUANTITY
  ======================================================= */

  if (
    !quantity
  ) {
    errors.push(
      "Quantity is required"
    );
  } else {
    const numericQuantity =
      Number(
        quantity
      );

    if (
      !Number.isFinite(
        numericQuantity
      ) ||
      numericQuantity <= 0
    ) {
      errors.push(
        "Quantity must be greater than 0"
      );
    }
  }


  /* =======================================================
     DIMENSION
  ======================================================= */

  if (
    !dimension
  ) {
    errors.push(
      "Dimension is required"
    );
  }


  if (
    errors.length
  ) {
    throw new Error(
      errors.join(
        ", "
      )
    );
  }

  return true;
};


/* =========================================================
   CHECK ALLOWED REQUEST FIELDS
========================================================= */

const validateAllowedFields = (
  payload,
  allowedFields,
  actionName
) => {
  if (
    !isPlainObject(
      payload
    )
  ) {
    throw new Error(
      `Invalid SBE Germany ${actionName} payload`
    );
  }

  const allowed =
    new Set(
      allowedFields
    );

  const restrictedFields =
    Object.keys(
      payload
    ).filter(
      (
        field
      ) =>
        !allowed.has(
          field
        )
    );

  if (
    restrictedFields.length >
    0
  ) {
    throw new Error(
      `Restricted SBE Germany field(s): ${restrictedFields.join(
        ", "
      )}`
    );
  }

  return true;
};


/* =========================================================
   VALIDATE CREATE PAYLOAD

   Frontend is allowed to send ONLY:

   {
     mtcProvider: "sbe_germany",
     grade: "...",
     customerName: "...",
     quantity: "...",
     dimension: "..."
   }

   Everything else is generated/rebuilt by backend.
========================================================= */

const validateSbeCreatePayload = (
  payload = {}
) => {
  validateAllowedFields(
    payload,

    [
      "mtcProvider",
      "grade",
      "customerName",
      "quantity",
      "dimension",
    ],

    "create"
  );


  /* =======================================================
     PROVIDER
  ======================================================= */

  if (
    payload.mtcProvider !==
      undefined &&
    cleanText(
      payload.mtcProvider
    ).toLowerCase() !==
      SBE_PROVIDER
  ) {
    throw new Error(
      "Invalid MTC provider for SBE Germany certificate"
    );
  }


  /* =======================================================
     COMPLETE CREATE VALIDATION
  ======================================================= */

  validateSbeEditableFields(
    {
      grade:
        payload.grade,

      customerName:
        payload.customerName,

      quantity:
        payload.quantity,

      dimension:
        payload.dimension,
    }
  );


  /*
   * Confirm grade config can actually
   * be loaded.
   */
  getSbeGradeConfig(
    payload.grade
  );


  return true;
};


/* =========================================================
   VALIDATE UPDATE PAYLOAD

   After creation user may change ONLY:

   - customerName
   - quantity
   - dimension

   Grade cannot change.
   Generated values cannot change.
   Controlled values cannot change.
========================================================= */

const validateSbeUpdatePayload = (
  payload = {}
) => {
  validateAllowedFields(
    payload,

    [
      "mtcProvider",
      "customerName",
      "quantity",
      "dimension",
    ],

    "update"
  );


  /* =======================================================
     PROVIDER
  ======================================================= */

  if (
    payload.mtcProvider !==
      undefined &&
    cleanText(
      payload.mtcProvider
    ).toLowerCase() !==
      SBE_PROVIDER
  ) {
    throw new Error(
      "MTC provider cannot be changed"
    );
  }


  /* =======================================================
     CUSTOMER NAME
  ======================================================= */

  if (
    payload.customerName !==
    undefined
  ) {
    const customerName =
      cleanText(
        payload.customerName
      );

    if (
      !customerName
    ) {
      throw new Error(
        "Customer Name cannot be empty"
      );
    }
  }


  /* =======================================================
     QUANTITY
  ======================================================= */

  if (
    payload.quantity !==
    undefined
  ) {
    const quantity =
      cleanText(
        payload.quantity
      );

    if (
      !quantity
    ) {
      throw new Error(
        "Quantity cannot be empty"
      );
    }

    const numericQuantity =
      Number(
        quantity
      );

    if (
      !Number.isFinite(
        numericQuantity
      ) ||
      numericQuantity <= 0
    ) {
      throw new Error(
        "Quantity must be greater than 0"
      );
    }
  }


  /* =======================================================
     DIMENSION
  ======================================================= */

  if (
    payload.dimension !==
    undefined
  ) {
    const dimension =
      cleanText(
        payload.dimension
      );

    if (
      !dimension
    ) {
      throw new Error(
        "Dimension cannot be empty"
      );
    }
  }


  return true;
};


/* =========================================================
   EXPORT
========================================================= */

module.exports = {
  SBE_PROVIDER,

  SBE_FIXED_VALUES,

  SBE_CHEMICAL_ORDER,

  SBE_GRADE_CONFIG,

  /*
   * Keep old frontend permissions export.
   */
  SBE_FRONTEND_PERMISSIONS,

  /*
   * Required by new separated
   * sbeGermanyMtcService.js.
   */
  SBE_FRONTEND_RULES,

  getSbeGradeConfig,

  getSbeGrades,

  buildSbeGradeFormData,

  /*
   * Old validator kept for compatibility.
   */
  validateSbeEditableFields,

  /*
   * New separated-service validators.
   */
  validateSbeCreatePayload,

  validateSbeUpdatePayload,
};